app_version: latest
capabilities: []
categories:
- productivity
description: Logseq is a privacy-first, open-source platform for knowledge management
  and collaboration.
home: https://logseq.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/logseq/icons/icon.png
keywords:
- knowledge
- management
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: logseq
run_as_context:
- description: Logseq runs as any non-root user.
  gid: 568
  group_name: logseq
  uid: 568
  user_name: logseq
screenshots: []
sources:
- https://github.com/logseq/logseq
title: Logseq
train: community
version: 1.0.5
