app_version: 2.4.62
capabilities: []
categories:
- storage
description: WebDAV is a set of extensions to the HTTP protocol which allows users
  to collaboratively edit and manage files on remote web servers.
home: http://www.webdav.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/webdav/icons/icon.png
keywords:
- webdav
- file-sharing
lib_version: 1.0.0
lib_version_hash: f7903e411b2a8506ba633c8301fa97f3f42398967f0123e668db9f92b286f4a6
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: webdav
run_as_context:
- description: WebDAV runs as any non-root user.
  gid: 568
  group_name: webdav
  uid: 568
  user_name: webdav
screenshots: []
sources:
- http://www.webdav.org/
title: WebDAV
train: community
version: 1.0.0
