resources:
  limits:
    cpus: 2.0
    memory: 4096

webdav:
  auth_type: none
  username: ''
  password: ''
  additional_browser_matches: []
  additional_envs: []
network:
  host_network: false
  enable_http: false
  http_port: 30034
  enable_https: false
  certificate_id:
  https_port: 30035

run_as:
  user: 568
  group: 568

storage:
  shares: []
