app_version: v2.53.0
capabilities: []
categories:
- monitoring
description: The Prometheus monitoring system and time series database.
home: https://prometheus.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/prometheus/icons/icon.png
keywords:
- metrics
- prometheus
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: prometheus
run_as_context:
- description: Prometheus runs as any non-root user.
  gid: 568
  group_name: prometheus
  uid: 568
  user_name: prometheus
screenshots:
- https://media.sys.truenas.net/apps/prometheus/screenshots/screenshot1.png
sources:
- https://github.com/prometheus/prometheus
- https://github.com/truenas/charts/tree/master/charts/prometheus
- https://prometheus.io
title: Prometheus
train: stable
version: 1.0.6
