app_version: 1.33.2
capabilities: []
categories:
- media
description: Overseerr is a free and open source software application for managing
  requests for your media library.
home: https://github.com/sct/overseerr
host_mounts: []
icon: https://media.sys.truenas.net/apps/overseerr/icons/icon.svg
keywords:
- media
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: overseerr
run_as_context:
- description: Overseerr runs as any non-root user.
  gid: 568
  group_name: overseerr
  uid: 568
  user_name: overseerr
screenshots: []
sources:
- https://hub.docker.com/r/sctx/overseerr
- https://github.com/sct/overseerr
title: Overseerr
train: community
version: 1.0.5
