app_version: 0.9.3
capabilities: []
categories:
- productivity
description: Homepage is a modern, secure, highly customizable application dashboard.
home: https://gethomepage.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/homepage/icons/icon.png
keywords:
- dashboard
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: homepage
run_as_context:
- description: Homepage runs as any non-root user.
  gid: 1000
  group_name: homepage
  uid: 1000
  user_name: homepage
screenshots:
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot5.png
- https://media.sys.truenas.net/apps/homepage/screenshots/screenshot6.png
sources:
- https://gethomepage.dev/
- https://github.com/benphelps/homepage
title: Homepage
train: community
version: 1.0.5
