app_version: v1.4.230
capabilities: []
categories:
- productivity
description: Mumble is a free, open source, low latency, high quality voice chat application.
home: https://www.mumble.info/
host_mounts: []
icon: https://media.sys.truenas.net/apps/mumble/icons/icon.svg
keywords:
- voice
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: mumble
run_as_context:
- description: Mumble runs as a non-root user.
  gid: 1000
  group_name: mumble
  uid: 1000
  user_name: mumble
screenshots: []
sources:
- https://github.com/mumble-voip/mumble-docker
- https://www.mumble.info/
title: Mumble
train: community
version: 1.0.5
