app_version: 2024-07-16T23-46-41Z
capabilities: []
categories:
- storage
description: The Object Store for AI Data Infrastructure
home: https://min.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/minio/icons/icon.png
keywords:
- storage
- object-storage
- S3
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: minio
run_as_context:
- description: Minio runs as any non-root user.
  gid: 473
  group_name: minio
  uid: 473
  user_name: minio
screenshots:
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot3.png
sources:
- https://github.com/minio/minio
title: MinIO
train: stable
version: 1.0.6
