app_version: 2024.6.1
capabilities: []
categories:
- network
description: Cloudflared is a client for Cloudflare Tunnel, a daemon that exposes
  private services through the Cloudflare edge.
home: https://github.com/cloudflare/cloudflared
host_mounts: []
icon: https://media.sys.truenas.net/apps/cloudflared/icons/icon.png
keywords:
- network
- cloudflare
- tunnel
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: cloudflared
run_as_context:
- description: Cloudflared runs as any non-root user.
  gid: 568
  group_name: cloudflared
  uid: 568
  user_name: cloudflared
screenshots: []
sources:
- https://github.com/cloudflare/cloudflared
- https://hub.docker.com/r/cloudflare/cloudflared
title: Cloudflared
train: community
version: 1.0.5
