app_version: 4.6.5
capabilities: []
categories:
- media
description: The qBittorrent project aims to provide an open-source software alternative
  to mTorrent.
home: https://www.qbittorrent.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/qbittorrent/icons/icon.png
keywords:
- media
- torrent
- download
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: qbittorrent
run_as_context:
- description: qBittorrent runs as any non-root user.
  gid: 568
  group_name: qbittorrent
  uid: 568
  user_name: qbittorrent
screenshots:
- https://media.sys.truenas.net/apps/qbittorrent/screenshots/screenshot1.png
sources:
- https://github.com/onedr0p/containers/tree/main/apps/qbittorrent
- https://www.qbittorrent.org/
title: qBittorrent
train: community
version: 1.0.10
