app_version: latest
capabilities:
- description: MineOS requires this ability to change ownership of files.
  name: CHOWN
- description: MineOS requires this ability to bypass file permissions.
  name: DAC_OVERRIDE
- description: MineOS requires this ability to bypass file permissions for it's sub-processes.
  name: FOWNER
- description: MineOS requires this ability to switch group for sub-processes.
  name: SETGID
- description: MineOS requires this ability to switch user for sub-processes.
  name: SETUID
categories:
- games
description: MineOS is a server front-end to ease managing Minecraft administrative
  tasks.
home: https://github.com/hexparrot/mineos-node
host_mounts: []
icon: https://media.sys.truenas.net/apps/mineos/icons/icon.png
keywords:
- minecraft
lib_version: 1.0.0
lib_version_hash: f64fc13a3ba5aa5290a6d624be183172f7c68841745cfb14a727a29e0a683efd
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: mineos
run_as_context:
- description: MineOS runs as root user.
  gid: 0
  group_name: root
  uid: 0
  user_name: root
screenshots:
- https://media.sys.truenas.net/apps/mineos/screenshots/screenshot1.png
sources:
- https://hub.docker.com/r/hexparrot/mineos/
- https://github.com/hexparrot/mineos-node
title: MineOS
train: community
version: 1.0.5
