name: Renovate

on:
  workflow_dispatch:

concurrency:
  group: renovate
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.7
        env:
          RENOVATE_PR_HOURLY_LIMIT: 10
          LOG_LEVEL: "debug"
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
          mount-docker-socket: true
      - name: cat
        shell: bash
        run: |
          cat /tmp/renovate.log
          cat /tmp/renovate-cmd.log
